import React from 'react'
import { Accordion } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.css'
const LPSsix = () => {
  return (
    <div className="LPSsixMAIN">
      <div className="LPSsixMAIN-L">
        <h1>Still have questions?</h1>
      </div>
      <div className="LPSsixMAIN-R">
        <Accordion defaultActiveKey="0">
          <Accordion.Item eventKey="0">
            <Accordion.Header>How does Berrywise work?</Accordion.Header>
            <Accordion.Body>
              We would love for you to check out how berrywise works{' '}
              <a href="#">here.</a>
            </Accordion.Body>
          </Accordion.Item>
          <Accordion.Item eventKey="1">
            <Accordion.Header>
              Is Berrywise in control of my funds?
            </Accordion.Header>
            <Accordion.Body>
              No, Berrywise only recommends a portfolio of stocks or any other
              asset mix. We redirect you to your favourite broker's website for
              you to execute the Berrywise recommended portfolio. You remain in
              full control of your funds and even the assets in your portfolio.{' '}
              <a href="#">Learn more</a>
            </Accordion.Body>
          </Accordion.Item>
          <Accordion.Item eventKey="2">
            <Accordion.Header>
              Can I speak to a real human for guidance?
            </Accordion.Header>
            <Accordion.Body>
              Yes, although not for Investment advice, We've Berrywise for that.
              You can connect with our team on {" "} <a href="#">discord</a> . We'll help you
              understand Berrywise, Help you deal with nasty software glitches
              or Just drop in for meme wars. Need help navigating the Berrywise
              platform?. Check <a href="#">here</a>
            </Accordion.Body>
          </Accordion.Item>
          <Accordion.Item eventKey="3">
            <Accordion.Header>
              Is there a minimum investment value?
            </Accordion.Header>
            <Accordion.Body>
              Yes, There is a minimum Investment value of INR 2,50,000/-. Why?.
              To give our user's best balance of diversification and risk
              aversion over long term. Berrywise personalised portfolio
              generated by our quantitative algorithms usually consists of many
              securities and multiple asset classes. Find out why we've this
              criteria <a href="#">here</a>
            </Accordion.Body>
          </Accordion.Item>
          <Accordion.Item eventKey="4">
            <Accordion.Header>I have more questions!</Accordion.Header>
            <Accordion.Body>
              We would love to answer queries you've regarding Berrywise, email
              us at hello@berrywise.ai or you can refer our {" "} <a href="#">help</a>  page.
            </Accordion.Body>
          </Accordion.Item>
        </Accordion>
      </div>
    </div>
  )
}

export default LPSsix
